webpackJsonp([17],{

/***/ 1703:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "通用表单"
    ],
    [
      "h2",
      "何时使用"
    ],
    [
      "ul",
      [
        "li",
        [
          "p",
          "快速构建表单"
        ]
      ]
    ],
    [
      "p",
      "引用方式："
    ],
    [
      "pre",
      {
        "lang": "javascript",
        "highlighted": "<span class=\"token keyword\">import</span> <span class=\"token punctuation\">{</span> XForm <span class=\"token punctuation\">}</span> <span class=\"token keyword\">from</span> <span class=\"token string\">'mhc-antd-admin'</span><span class=\"token punctuation\">;</span>"
      },
      [
        "code",
        "import { XForm } from 'mhc-antd-admin';"
      ]
    ]
  ],
  "meta": {
    "category": "Components",
    "type": "Data Display",
    "subtitle": "通用表单",
    "cols": 1,
    "title": "XForm",
    "filename": "components/XForm/index.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#何时使用",
          "title": "何时使用"
        },
        "何时使用"
      ]
    ],
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "items"
          ],
          [
            "td",
            "表单项配置"
          ],
          [
            "td",
            "Array"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "actionsConfig"
          ],
          [
            "td",
            "操作项配置"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "loading"
          ],
          [
            "td",
            "提交按钮的 ",
            [
              "code",
              "Loading"
            ],
            " 状态"
          ],
          [
            "td",
            "Boolean"
          ],
          [
            "td",
            "false"
          ]
        ]
      ]
    ],
    [
      "h3",
      "items"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "label"
          ],
          [
            "td",
            "表单项的 ",
            [
              "code",
              "label"
            ]
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "layout"
          ],
          [
            "td",
            "表单项的布局"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "itemLayout"
          ],
          [
            "td",
            [
              "code",
              "label"
            ],
            " 与 ",
            [
              "code",
              "input"
            ],
            " 的布局"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            [
              "code",
              "{ labelCol: { md: { span: 8 }}, wrapperCol: { md: { span: 16 }} }"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "formItem"
          ],
          [
            "td",
            "表单项"
          ],
          [
            "td",
            "Node"
          ],
          [
            "td",
            "false"
          ]
        ]
      ]
    ],
    [
      "h3",
      "actionsConfig"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "layout"
          ],
          [
            "td",
            "操作项的布局"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "submitText"
          ],
          [
            "td",
            "确认文本"
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onSubmit"
          ],
          [
            "td",
            "提交的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            [
              "code",
              "(form) => {}"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "onReset"
          ],
          [
            "td",
            "重置的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            [
              "code",
              "(form) => {}"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "onCancel"
          ],
          [
            "td",
            "取消的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            [
              "code",
              "(form) => {}"
            ]
          ]
        ]
      ]
    ],
    [
      "p",
      "items 配置示例"
    ],
    [
      "pre",
      {
        "lang": "javascript",
        "highlighted": "<span class=\"token keyword\">export</span> <span class=\"token keyword\">const</span> getFormItemsConfig <span class=\"token operator\">=</span> context <span class=\"token operator\">=</span><span class=\"token operator\">></span> <span class=\"token punctuation\">{</span>\n  <span class=\"token keyword\">const</span> <span class=\"token punctuation\">{</span> data <span class=\"token punctuation\">}</span> <span class=\"token operator\">=</span> context<span class=\"token punctuation\">.</span>state<span class=\"token punctuation\">;</span>\n  <span class=\"token keyword\">return</span> <span class=\"token punctuation\">[</span>\n    <span class=\"token punctuation\">{</span>\n      label<span class=\"token punctuation\">:</span> <span class=\"token string\">'用户名'</span><span class=\"token punctuation\">,</span>\n      layout<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> md<span class=\"token punctuation\">:</span> <span class=\"token number\">24</span> <span class=\"token punctuation\">}</span><span class=\"token punctuation\">,</span>\n      itemLayout<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span>\n        labelCol<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> md<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> span<span class=\"token punctuation\">:</span> <span class=\"token number\">4</span> <span class=\"token punctuation\">}</span><span class=\"token punctuation\">}</span><span class=\"token punctuation\">,</span>\n        wrapperCol<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> md<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> span<span class=\"token punctuation\">:</span> <span class=\"token number\">18</span> <span class=\"token punctuation\">}</span><span class=\"token punctuation\">}</span>\n      <span class=\"token punctuation\">}</span><span class=\"token punctuation\">,</span>\n      formItem<span class=\"token punctuation\">:</span> getFieldDecorator <span class=\"token operator\">=</span><span class=\"token operator\">></span> <span class=\"token punctuation\">{</span>\n        <span class=\"token keyword\">return</span> <span class=\"token function\">getFieldDecorator</span><span class=\"token punctuation\">(</span><span class=\"token string\">'uname'</span><span class=\"token punctuation\">,</span> <span class=\"token punctuation\">{</span>\n          initialValue<span class=\"token punctuation\">:</span> data<span class=\"token punctuation\">.</span>name <span class=\"token operator\">||</span> <span class=\"token string\">''</span>\n        <span class=\"token punctuation\">}</span><span class=\"token punctuation\">)</span><span class=\"token punctuation\">(</span><span class=\"token operator\">&lt;</span>Input placeholder<span class=\"token operator\">=</span><span class=\"token string\">\"请输入\"</span><span class=\"token operator\">/</span><span class=\"token operator\">></span><span class=\"token punctuation\">)</span><span class=\"token punctuation\">;</span>\n      <span class=\"token punctuation\">}</span><span class=\"token punctuation\">,</span>\n    <span class=\"token punctuation\">}</span>\n  <span class=\"token punctuation\">]</span>\n<span class=\"token punctuation\">}</span>"
      },
      [
        "code",
        "export const getFormItemsConfig = context => {\n  const { data } = context.state;\n  return [\n    {\n      label: '用户名',\n      layout: { md: 24 },\n      itemLayout: {\n        labelCol: { md: { span: 4 }},\n        wrapperCol: { md: { span: 18 }}\n      },\n      formItem: getFieldDecorator => {\n        return getFieldDecorator('uname', {\n          initialValue: data.name || ''\n        })(<Input placeholder=\"请输入\"/>);\n      },\n    }\n  ]\n}"
      ]
    ],
    [
      "p",
      "actionsConfig 配置示例"
    ],
    [
      "pre",
      {
        "lang": "javascript",
        "highlighted": "<span class=\"token keyword\">export</span> <span class=\"token keyword\">const</span> getSubmitConfig <span class=\"token operator\">=</span> context <span class=\"token operator\">=</span><span class=\"token operator\">></span> <span class=\"token punctuation\">{</span>\n  <span class=\"token keyword\">return</span> <span class=\"token punctuation\">{</span>\n    layout<span class=\"token punctuation\">:</span> <span class=\"token punctuation\">{</span> md<span class=\"token punctuation\">:</span> <span class=\"token number\">8</span> <span class=\"token punctuation\">}</span><span class=\"token punctuation\">,</span>\n    onSubmit<span class=\"token punctuation\">:</span> context<span class=\"token punctuation\">.</span>onSubmit<span class=\"token punctuation\">,</span>\n    submitText<span class=\"token punctuation\">:</span> <span class=\"token string\">'查询'</span><span class=\"token punctuation\">,</span>\n  <span class=\"token punctuation\">}</span><span class=\"token punctuation\">;</span>\n<span class=\"token punctuation\">}</span><span class=\"token punctuation\">;</span>"
      },
      [
        "code",
        "export const getSubmitConfig = context => {\n  return {\n    layout: { md: 8 },\n    onSubmit: context.onSubmit,\n    submitText: '查询',\n  };\n};"
      ]
    ]
  ]
};

/***/ })

});
//# sourceMappingURL=index.md.js.map