webpackJsonp([19],{

/***/ 1699:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "滑动展示层"
    ],
    [
      "h2",
      "何时使用"
    ],
    [
      "ul",
      [
        "li",
        [
          "p",
          "可上下左右滑动出来显示，带 ",
          [
            "code",
            "mask"
          ],
          " 遮罩层，常用于侧滑展示详情。"
        ]
      ]
    ],
    [
      "p",
      "引用方式："
    ],
    [
      "pre",
      {
        "lang": "javascript",
        "highlighted": "<span class=\"token keyword\">import</span> <span class=\"token punctuation\">{</span> Offcanvas <span class=\"token punctuation\">}</span> <span class=\"token keyword\">from</span> <span class=\"token string\">'mhc-antd-admin'</span><span class=\"token punctuation\">;</span>"
      },
      [
        "code",
        "import { Offcanvas } from 'mhc-antd-admin';"
      ]
    ]
  ],
  "meta": {
    "category": "Components",
    "type": "Data Display",
    "subtitle": "滑动展示层",
    "title": "Offcanvas",
    "filename": "components/Offcanvas/index.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#何时使用",
          "title": "何时使用"
        },
        "何时使用"
      ]
    ],
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "show"
          ],
          [
            "td",
            "显示隐藏，由外部控制"
          ],
          [
            "td",
            "bool"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "position"
          ],
          [
            "td",
            "从哪个位置滑出 ",
            [
              "code",
              "top/left/bottom/center"
            ]
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "center"
          ]
        ],
        [
          "tr",
          [
            "td",
            "animate"
          ],
          [
            "td",
            "显示时的动画，",
            [
              "code",
              "slide-in-top / slide-in-bottom / zoom-in"
            ]
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            [
              "code",
              "slide-in-top"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "closeByMask"
          ],
          [
            "td",
            "是否可以点击遮罩关闭"
          ],
          [
            "td",
            "bool"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClose"
          ],
          [
            "td",
            "关闭事件，组件关闭调用这个事件"
          ],
          [
            "td",
            "func"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onShow"
          ],
          [
            "td",
            "显示之后的回调"
          ],
          [
            "td",
            "func"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onHide"
          ],
          [
            "td",
            "关闭之后的回调"
          ],
          [
            "td",
            "func"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onFirstShow"
          ],
          [
            "td",
            "用于第一次显示时的回调"
          ],
          [
            "td",
            "func"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "hideMask"
          ],
          [
            "td",
            "用于隐藏遮罩，使其透明"
          ],
          [
            "td",
            "bool"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "height"
          ],
          [
            "td",
            "浮层的高"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "width"
          ],
          [
            "td",
            "浮层的宽"
          ],
          [
            "td",
            "String"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

});
//# sourceMappingURL=index.md.js.map